apiVersion: v1
kind: Service
metadata:
  name: service-hello-dev
spec:
  type: NodePort
  selector:
    app: hello-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31069
